# Generated by Django 4.1.7 on 2023-11-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_task_email_task_notify_task_time_task_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
